name: Sync Fork

on:
  schedule:
    - cron: '* * * * *' # Ejecuta todos los días a las 00:00 UTC
  workflow_dispatch: # Permite activarlo manualmente desde la pestaña "Actions"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          ref: gh-pages # O la rama que quieras actualizar (ej. master)

      - name: Sync Fork
        uses: aormsby/Fork-Sync-With-Upstream-action@v3
        with:
          upstream_sync_repo: izugarri2/steviewonder
          upstream_sync_branch: gh-pages # Rama original de la que tirar cambios
          target_sync_branch: gh-pages # Tu rama en el fork a actualizar
          upstream_pull_args: '--allow-unrelated-histories'
          # token: ${{ secrets.GITHUB_TOKEN }} # (Opcional) Necesario si el repo es privado
